# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SparksCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: 👀 List all files
      run: ls
    - name: 🛠️ Build Sparks Meal&Receipes
      run: mvn clean install --file mealsandrecipes/pom.xml
    - name: 💅 Style Checker
      run: |
        cd mealsandrecipes
        ./mvnw checkstyle:check
    - name: 🚀 Run Unit Tests
      run: |
        cd mealsandrecipes
        ./mvnw test
    - name: 🐛 Static Analysis
      run: |
        cd mealsandrecipes
        mvn spotbugs:check
      continue-on-error: true # we should disable this once we fix the spotbug warnings